server:
  address : localhost
  port : 8080

# MySQL 연동 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shootformoney
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    show_sql: true

logging.level:
  org.hibernate.SQL: debug

# football-data.org API 연동
football:
  api:
    key: 26d128ed6a694c3699f698df83a4eb54
    base-url: https://api.football-data.org/v4