server:
  address : localhost
  port : 8080

# MySQL 연동 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shootformoney
    username: root
    password: aA!123456

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    show_sql: true

  # thymeleaf 설정
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mvc:
    static-path-pattern: /static/**

  # mail 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: crazymin180@gmail.com
    password: zumb zjje zocn cdmb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
custom:
  siteName: shootformoney
  siteMainUri: http://localhost:8080
  emailFrom: test@localhost
  emailFromName: admin

logging.level:
  org.hibernate.SQL: debug